export default {
  login: 'sseyler0119',
  id: 18663457,
  node_id: 'MDQ6VXNlcjE4NjYzNDU3',
  avatar_url: 'https://avatars.githubusercontent.com/u/18663457?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/sseyler0119',
  html_url: 'https://github.com/sseyler0119',
  followers_url: 'https://api.github.com/users/sseyler0119/followers',
  following_url:
    'https://api.github.com/users/sseyler0119/following{/other_user}',
  gists_url: 'https://api.github.com/users/sseyler0119/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/sseyler0119/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/sseyler0119/subscriptions',
  organizations_url: 'https://api.github.com/users/sseyler0119/orgs',
  repos_url: 'https://api.github.com/users/sseyler0119/repos',
  events_url: 'https://api.github.com/users/sseyler0119/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/sseyler0119/received_events',
  type: 'User',
  site_admin: false,
  name: 'Serena Seyler',
  company: null,
  blog: '',
  location: 'Portland, Oregon',
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 1,
  following: 4,
  created_at: '2016-04-25T15:44:11Z',
  updated_at: '2022-11-22T04:30:12Z',
};